---
title: "디지털 글쓰기"
subtitle: "챗GPT 엑셀"
description: |
  챗GPT 엑셀 스프레드쉬트 기본기를 탄탄히 다져보자.
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
#title-block-banner: "#562457"
format:
  html:
    theme: flatly
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
filters:
   - lightbox
lightbox: auto
bibliography: bibliography.bib
link-citations: true
csl: apa-single-spaced.csl
knitr:
  opts_chunk: 
    message: false
    warning: false
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---


# 학점 계산

연속형 값을 갖는 변수를 이산형으로 변환하는 경우가 흔히 있다.
예를 들어, 성정을 0~100점 사이 연속형 값 대신에 수우미양가 와 같은 
이산형 값으로 데이터를 변환하는 것이 훨씬 더 직관적이다.
또다른 예로 의원들의 의정활동을 정량적으로 평가하여 점수를 매긴 후에 
최우수/우수/중간/미흡 등과 같이 척도를 바꾸는 것이 많이 사용되는 사례다.

:::{.callout-note collapse="false"}
### 프롬프트: 10명의 학생이 통계학 수업을 수강했습니다. 평가를 위해 출석(10%), 중간고사(30%), 기말고사(30%), 과제(30%) 점수가 배정되어 있습니다. 데이터를 csv 형태로 임의로 만드세요. 90점 이상은 A, 80점 이상은 B, 70점 이상은 C 그이하는 F를 주는 엑셀 함수를 작성하세요.


먼저, 10명의 학생들에 대한 임의의 데이터를 csv 형태로 만들어 보겠습니다. 이 데이터는 학생의 이름, 출석, 중간고사, 기말고사, 그리고 과제 점수를 포함하고 있습니다.

```
이름,출석,중간고사,기말고사,과제
학생1,10,70,80,90
학생2,9,85,75,80
학생3,10,80,90,70
학생4,8,70,75,80
학생5,10,85,90,85
학생6,9,70,80,70
학생7,10,75,85,90
학생8,9,85,80,85
학생9,10,90,85,80
학생10,8,80,85,75
```

다음으로, 각 학생의 총점을 계산하는 엑셀 함수를 작성해야 합니다. 이는 각 학생의 출석, 중간고사, 기말고사, 그리고 과제 점수에 가중치를 적용하여 계산됩니다.

예를 들어, '학생1'의 경우, 총점은 다음과 같이 계산됩니다:

출석 점수: 10 * 0.1 = 1
중간고사 점수: 70 * 0.3 = 21
기말고사 점수: 80 * 0.3 = 24
과제 점수: 90 * 0.3 = 27

따라서, 학생1의 총점은 1 + 21 + 24 + 27 = 73 점이 됩니다.

이러한 계산을 엑셀에서 수행하는 함수는 다음과 같이 작성할 수 있습니다:

```
= B2*0.1 + C2*0.3 + D2*0.3 + E2*0.3
```

마지막으로, 각 학생의 성적을 할당하는 엑셀 함수를 작성해야 합니다. 이 함수는 총점에 따라 학생에게 'A', 'B', 'C', 또는 'F' 성적을 할당합니다.

이를 수행하는 엑셀 함수는 다음과 같이 작성할 수 있습니다:

```
=IF(F2>=90, "A", IF(F2>=80, "B", IF(F2>=70, "C", "F")))
```

위의 함수에서 'F2'는 총점이 계산된 엑셀의 셀을 나타냅니다. 이 함수는 'F2' 셀의 값이 90 이상인지, 80 이상인지, 70 이상인지 확인하고, 각 경우에 따라 적절한 성적을 할당합니다. 만약 'F2' 셀의 값이 70 미만인경우, 학생에게 'F' 성적이 할당됩니다.

이러한 방식으로, 엑셀에서 학생들의 성적을 계산하고 할당하는 함수를 작성할 수 있습니다.
:::


```{r}
library(tidyverse)
library(googlesheets4)
library(gt)

gpa <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1PLIvo8hfZQ_a15NAMiPOAXuTp40ngVIwGRaIh4qaSRo/edit#gid=0", sheet = "학점")

gpa %>% 
  gt::gt() %>% 
  cols_align(align = "center", 
             columns = everything())
```


# 중복제거

:::{.callout-note collapse="false"}
### 바드: 공장에 자재가 일자별로 입고되는 데이터를 20개 만들어주세요. 단, 입고자재 10%는 중복되도록 생성하는데 다음과 형태로 출력해주세요. 중복은 입고일자, 자재명, 자재번호, 담당부서, 수량이 모두 동일해야 합니다. 자재명과 담당부서도 실제처럼 작성해야 합니다.
> 입고일자,자재명,자재번호,담당부서,수량,단위, 중복여부

```
입고일자,자재명,자재번호,담당부서,수량,단위,중복여부
2023-05-23,나사,123456,생산부,100개,개,N
2023-05-23,볼트,789012,품질부,200개,개,N
2023-05-23,너트,345678,영업부,300개,개,N
2023-05-23,와셔,987654,연구개발부,400개,개,N
2023-05-23,못,654321,관리부,500개,개,N
2023-05-23,자재1,123456,생산부,100개,개,Y
2023-05-23,자재2,789012,품질부,200개,개,Y
2023-05-23,자재3,345678,영업부,300개,개,Y
2023-05-23,자재4,987654,연구개발부,400개,개,Y
2023-05-23,자재5,654321,관리부,500개,개,Y
2023-05-24,나사,123456,생산부,100개,개,N
2023-05-24,볼트,789012,품질부,200개,개,N
2023-05-24,너트,345678,영업부,300개,개,N
2023-05-24,와셔,987654,연구개발부,400개,개,N
2023-05-24,못,654321,관리부,500개,개,N
2023-05-25,자재1,123456,생산부,100개,개,N
2023-05-25,자재2,789012,품질부,200개,개,N
2023-05-25,자재3,345678,영업부,300개,개,N
2023-05-25,자재4,987654,연구개발부,400개,개,N
2023-05-25,자재5,654321,관리부,500개,개,N
```

:::

